services:
  server:
    image: 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/a2-pairs-5-a2-assessment2-repo:latest
    ports:
      - "3010:3010"
    env_file:
      - .env
    depends_on:
      - redis

  web:
    image: 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/api-web:latest
    ports:
      - "3009:3009"
    depends_on:
      - server
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
volumes:
  db_data:
