services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=pass
      - DB_NAME=tasksdb
    depends_on:
      - db

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3009:3009"
    depends_on:
      - server
  db:
    image: mariadb:11
    restart: always
    environment:
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3008:3008"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
